### ISSUE TITLE
lacking debug information

### ISSUE THREAD

**Issue by bjm88** [openid/ruby-openid#101]
Getting a weird error with one customer doing SSO...
case oidresp.status
      when OpenID::Consumer::FAILURE
        if oidresp.display_identifier
          handle_error "OpenID SSO Verification of #{oidresp.display_identifier} failed: #{oidresp.message}"
          return

is hitting failure....
display_identifier printing as https://blah.powerschool.com/oid/guardian/test1
and message printing as
 failed: No matching endpoint found after discovering https://Blah.powerschool.com/oid/guardian/test1

Only weird thing to me is the case sensitive mismatch on unix I'd guess from blah.powerschool.com to Blah.powerschool.com

could that be issue or does error mean something else?  How to get more info...

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
