### ISSUE TITLE
OpenID.fetch does not handle relative path redirects

### ISSUE THREAD

**Issue by tadaniels** [openid/ruby-openid#102]
This line 

https://github.com/openid/ruby-openid/blob/master/lib/openid/fetchers.rb#L237

does not account for a redirect that contains a relative path which should be supported.  

For reference see this Stackoverflow question regarding support for relative redirect paths http://stackoverflow.com/questions/8250259/is-a-302-redirect-to-relative-url-valid-or-invalid

Thanks

**Comment by tobiashm** [comment]
Thanks for the report. A pull-request with a suggestion for code change, or a (failing) test case would be much appreciated, if you have the time.

**Comment by tobiashm** [comment]
The recent specs for Location response header: https://tools.ietf.org/html/rfc7231#section-7.1.2

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
