### ISSUE TITLE
Printing error messages

### ISSUE THREAD

**Issue by Altantur** [openid/ruby-openid#105]
Hello, I'm facing this error quite long time. **It is happens when third party openID provider giving back response.** It is working fine but my error log is full of this kind of error. Any idea how to overcome is much appreciated.
```
App 27790 stderr: I, [2017-05-02T16:43:00.960007 #27900]  INFO -- OpenID: Error attempting to use stored discovery information: OpenID::TypeURIMismatch
App 27790 stderr: I, [2017-05-02T16:43:00.960042 #27900]  INFO -- OpenID: Attempting discovery to verify endpoint
App 27790 stderr: I, [2017-05-02T16:43:00.960067 #27900]  INFO -- OpenID: Performing discovery on 
```

**Comment by mlh758** [comment]
Seems to be relatd to #74

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
