### ISSUE TITLE
Trying to find a simple walk through on adding OIDC to a ruby application

### ISSUE THREAD

**Issue by CrowdHailer** [openid/ruby-openid#127]
Is there a simple guide for adding OpenID to an application.

Something at this level, and maybe for rails or perhaps it can be done at the rack level. https://dev.to/crowdhailer/adding-did-authentication-to-a-phoenix-web-app-18ec
I'm very familiar with OAuth and OIDC but could do with advice on working out what level it should be added to a rails application

p.s. I wrote the did.app article but something not tied to any particular auth provider would be useful

**Comment by mkasztelnik** [comment]
Take a look at [`omniauth`](https://github.com/omniauth/omniauth) and [`omniauth-openid`](https://github.com/omniauth/omniauth-openid).

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
