### ISSUE TITLE
Sreg arguments are lost during setup_needed phase

### ISSUE THREAD

**Issue by Nopik** [openid/ruby-openid#37]
When client is making immediate request, asking for extra arguments (e.g. "http://openid.net/extensions/sreg/1.1", optional = "email") and user is not authorized, setup_url is returned. OpenID::Server::CheckIDRequest is trying to clone itself for having immediate=false and then encoding to setup_url, but it is losing extra self.message.args, so when second setup request arrives, the args are lost and there is no way to get them back, but to send another request.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
