### ISSUE TITLE
Specifics of using gem with bundler

### ISSUE THREAD

**Issue by glebe** [openid/ruby-openid#48]
When including gem through bundler, one should use the following syntax:

> gem "ruby-openid", :require => 'openid'

to avoid problems like this on application start

> ActionDispatch::Session::SessionRestoreError (Session contains objects whose class definition isn't available.
> Remember to require the classes for all objects kept in the session.
> (Original exception: uninitialized constant OpenID [NameError])
> ):

**Comment by tobiashm** [comment]
Fixed by #112
