### ISSUE TITLE
ruby-openid v2.3.0 ignores assoc_handle when using open ID 2.0

### ISSUE THREAD

**Issue by bgeuken** [openid/ruby-openid#63]
We were having some encoding issues with openid and while looking at this I noticed that ruby-openid v2.3.0 is silently switching to stateless mode for openid 2.0.
Reading the [openid specs](http://openid.net/specs/openid-authentication-2_0.html) I would think that it is valid to use an association handle with openid 2.0.

The code that introduced the change was PR #53.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
