### ISSUE TITLE
please specify license of test data

### ISSUE THREAD

**Issue by ktdreyer** [openid/ruby-openid#64]
As part of a Fedora [package review](https://bugzilla.redhat.com/show_bug.cgi?id=1015778), @mtasaka pointed out that the license(s) of the files under `/test/data/` is somewhat unclear.

The `linkparse.txt` file seems to have been copied from the Python OpenID project: https://svn.apache.org/repos/asf/incubator/heraldry/libraries/python/openid/trunk/openid/test/linkparse.txt

The [license file](https://svn.apache.org/repos/asf/incubator/heraldry/libraries/python/openid/trunk/COPYING) for the Python OpenID project indicates that the files are available under the LGPLv2.1 or later license. However, the LICENSE file in ruby-openid makes no mention of this.

Can you please clarify this situation? Does ruby-openid distribute the files `/test/data/` files under LGPLv2.1+, or a different license (eg ASL 2.0)?

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
