### ISSUE TITLE
Fails when assoc request has a session_type of an empty string

### ISSUE THREAD

**Issue by aaronpk** [openid/ruby-openid#77]
pypi.python.org sends an assoc request with `session_type` set to an empty string.

Params sent are:

```
{"openid.mode"=>"associate", "openid.session_type"=>"", "openid.assoc_type"=>"HMAC-SHA1"}
```

According to the OpenID spec, `session_type` will be either blank or "DH-SHA1". In order to fix my provider code I had to override this value to "no-encryption" before letting the gem process the request.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
