### ISSUE TITLE
Digest::HMAC is deprecated in ruby 2.2

### ISSUE THREAD

**Issue by mattconnolly** [openid/ruby-openid#87]
Ruby 2.2 deprecates Digest::HMAC. See:

https://github.com/ruby/ruby/commit/24be1f1

As per the deprecation here, OpenSSL::HMAC should be used in preference to Digest::HMAC.

**Comment by tobiashm** [comment]
Dear maintainers:
This is fixed in #84 
Is there any chance of that being merged?

**Comment by jesperronn** [comment]
suggest you close this since #84 is now merged

**Comment by dennisreimann** [comment]
Yep, this will be fixed with the upcoming v2.7.0 - thanks!
