### ISSUE TITLE
rescue Exception

### ISSUE THREAD

**Issue by jhmoore** [openid/ruby-openid#95]
We just spent quite a long time trying to figure out why our login tests weren't failing in certain cases when we were expecting them to . . . turns out the answer is [the ruby-openid gem is rescuing `Exception` in several places](https://github.com/openid/ruby-openid/search?utf8=%E2%9C%93&q=%22rescue+exception%22&type=Code).  :finnadie:

**Comment by tobiashm** [comment]
Yes, this seems to be quite wrong.
Will take a look at it soon.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
