### ISSUE TITLE
Using memcache storage with Dalli

### ISSUE THREAD

**Issue by kamk** [openid/ruby-openid#99]
I'm using OpenID::Store::Memcache with Dalli::Client and getting this warning:
"Expiration interval too long for Memcached, converting to an expiration timestamp"

**Comment by tobiashm** [comment]
This seems to be an issue with Dalli, which misinterprets the timestamp as a relative time.
I'll file an issue with them.

**Comment by tobiashm** [comment]
Created pull-request for fixing Dalli's handling of expiration times: https://github.com/petergoldstein/dalli/pull/620
